from config.config import (
    BD_NAME, LIMIT_NOTE_TITLE, LIMIT_NOTE_TEXT,
    LIMIT_CATEGORY_TITLE, LIMIT_CATEGORY_SLUG,
    LIMIT_USERNAME, MEDIA, BASEDIR, MEDIA_DIR,
    SECRET_KEY, ALGORITHM, ACCESS_TOKEN_EXPIRE_MINUTES,
    pwd_context, oauth2_scheme
)